const fakeTabs = [
  {
    active: false,
    audible: false,
    autoDiscardable: true,
    discarded: false,
    favIconUrl: 'http://localhost:9000/assets/favicon/favicon.ico',
    groupId: -1,
    height: 980,
    highlighted: false,
    id: 1236,
    virtualId: '1236-opened-tab',
    incognito: false,
    index: 0,
    mutedInfo: {
      muted: false,
    },
    pinned: false,
    selected: false,
    status: 'complete',
    title: 'Bifrost Web App',
    url: 'http://localhost:9000/#/formulate',
    width: 1920,
    windowId: 251,
  },
  {
    active: false,
    audible: false,
    autoDiscardable: true,
    discarded: false,
    favIconUrl: '',
    groupId: -1,
    height: 980,
    highlighted: false,
    id: 1284,
    virtualId: '1284-opened-tab',
    incognito: false,
    index: 1,
    mutedInfo: {
      muted: false,
    },
    pinned: false,
    selected: false,
    status: 'complete',
    title: 'Extensions',
    url: 'chrome://extensions/',
    width: 1335,
    windowId: 251,
  },
  {
    active: true,
    audible: false,
    autoDiscardable: true,
    discarded: false,
    favIconUrl: 'https://www.google.com/favicon.ico',
    groupId: -1,
    height: 980,
    highlighted: true,
    id: 1290,
    virtualId: '1290-opened-tab',
    incognito: false,
    index: 2,
    mutedInfo: {
      muted: false,
    },
    pinned: false,
    selected: true,
    status: 'loading',
    title: 'asd - Google Search',
    url: 'https://www.google.com/search?q=asd&btnK=Google+Search&sxsrf=AOaemvLRnfSl0bNmqQnFt0y5DJr8B0GAgA%3A1637790450566&source=hp&ei=8rKeYYmeIMmIrwS-566gCQ&iflsig=ALs-wAMAAAAAYZ7BAhS2oqCt2WH2hya6C_XPES7djT-7',
    width: 1335,
    windowId: 251,
  },
  {
    active: false,
    audible: false,
    autoDiscardable: true,
    discarded: false,
    favIconUrl: 'https://swr.vercel.app/favicon/favicon-32x32.png',
    groupId: -1,
    height: 980,
    highlighted: false,
    id: 1094,
    virtualId: '1094-opened-tab',
    incognito: false,
    index: 3,
    mutedInfo: {
      muted: false,
    },
    pinned: false,
    selected: false,
    status: 'complete',
    title: 'API Options – SWR',
    url: 'https://swr.vercel.app/docs/options',
    width: 1920,
    windowId: 251,
  },
  {
    active: false,
    audible: false,
    autoDiscardable: true,
    discarded: false,
    favIconUrl: 'https://www.youtube.com/s/desktop/b6df0f3a/img/favicon_32x32.png',
    groupId: -1,
    height: 980,
    highlighted: false,
    id: 1080,
    virtualId: '1080-opened-tab',
    incognito: false,
    index: 4,
    mutedInfo: {
      muted: false,
    },
    pinned: false,
    selected: false,
    status: 'complete',
    title: 'midnight skateboarding with suna rintarou - YouTube',
    url: 'https://www.youtube.com/watch?v=AcNLDjfOl7g',
    width: 1920,
    windowId: 251,
  },
  {
    active: false,
    audible: false,
    autoDiscardable: true,
    discarded: false,
    favIconUrl: 'https://react-table.tanstack.com/_next/static/images/favicon-07c3e551b48272d4685be76a6a7fb11c.png',
    groupId: -1,
    height: 980,
    highlighted: false,
    id: 1206,
    virtualId: '1206-opened-tab',
    incognito: false,
    index: 5,
    mutedInfo: {
      muted: false,
    },
    pinned: false,
    selected: false,
    status: 'complete',
    title: 'API Reference: useSortBy | React Table | TanStack',
    url: 'https://react-table.tanstack.com/docs/api/useSortBy',
    width: 1920,
    windowId: 251,
  },
  {
    active: false,
    audible: false,
    autoDiscardable: true,
    discarded: false,
    groupId: -1,
    height: 980,
    highlighted: false,
    id: 1230,
    virtualId: '1230-opened-tab',
    incognito: false,
    index: 6,
    mutedInfo: {
      muted: false,
    },
    pinned: false,
    selected: false,
    status: 'complete',
    title: 'Bifrost Dev Board - Agile Board - JIRA',
    url: 'https://pantonexrite.atlassian.net/jira/software/c/projects/EFXW/boards/328?assignee=60b7507bbbe237006afa4bc7',
    width: 1920,
    windowId: 251,
  },
  {
    active: false,
    audible: false,
    autoDiscardable: true,
    discarded: false,
    favIconUrl: 'https://developer.chrome.com/images/meta/favicon-32x32.png',
    groupId: -1,
    height: 980,
    highlighted: false,
    id: 1276,
    virtualId: '1276-opened-tab',
    incognito: false,
    index: 7,
    mutedInfo: {
      muted: false,
    },
    pinned: false,
    selected: false,
    status: 'complete',
    title: 'chrome.tabs - Chrome Developers',
    url: 'https://developer.chrome.com/docs/extensions/reference/tabs/',
    width: 1920,
    windowId: 251,
  },
  {
    active: false,
    audible: false,
    autoDiscardable: true,
    discarded: false,
    favIconUrl: 'https://developer.chrome.com/images/meta/favicon-32x32.png',
    groupId: -1,
    height: 980,
    highlighted: false,
    id: 1283,
    virtualId: '1283-opened-tab',
    incognito: false,
    index: 8,
    mutedInfo: {
      muted: false,
    },
    pinned: false,
    selected: false,
    status: 'complete',
    title: 'chrome.tabs - Chrome Developers',
    url: 'https://developer.chrome.com/docs/extensions/reference/tabs/#method-query',
    width: 1920,
    windowId: 251,
  },
];

export default fakeTabs;
